[package]
name = "PayloadViewer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
bevy = "0.16.1"
bevy_panorbit_camera = "0.27.1"
rfd = "0.15.4"
bevy_obj = "0.16.1"
bevy_egui = "0.35.1"
